version: '3.9'

services:
  homebudget-web-api:
    image: ${DOCKER_REGISTRY-}homebudget-webapi
    container_name: homebudget-webapi
    build:
      context: .
      dockerfile: dockerfile
      args:
        - SONAR_TOKEN=${SONAR_TOKEN}
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - SONAR_TOKEN=${SONAR_TOKEN}
      - GITHUB_RUN_ID={GITHUB_RUN_ID}
      - PULL_REQUEST_ID=${PULL_REQUEST_ID}
      - PULL_REQUEST_SOURCE_BRANCH=${PULL_REQUEST_SOURCE_BRANCH}
      - PULL_REQUEST_TARGET_BRANCH=${PULL_REQUEST_TARGET_BRANCH}
    ports:
      - "5001:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - homebudget-sql-server
      - redis_server
      - sonarCube

  homebudget-sql-server:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: "${DOCKER_REGISTRY-}homebudget-sql-server"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SQL_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - ${SQL_VOLUME_PATH}:/var/opt/mssql/data

  flyway:
    image: flyway/flyway:latest
    depends_on:
      - homebudget-sql-server
    container_name: flyway-migration
    command: 
      -url=jdbc:sqlserver://homebudget-sql-server 
      -schemas=homebudget-schema
      -user=sa
      -password=${SQL_PASSWORD} 
      -connectRetries=10 migrate
    volumes:
      - ${FLYWAY_SCRIPTS_PATH}:/flyway/sql

  redis_server:
    image: redis:latest
    depends_on:
      - homebudget-sql-server
    container_name: homebudget-cache
    ports:
      - "6379:6379"
    
  sonarCube:
    image: sonarqube:latest
    depends_on:
      - homebudget-sql-server
    container_name: sonar-cube
    environment:
      SONAR_JDBC_USERNAME: sa
      SONAR_JDBC_PASSWORD: ${SQL_PASSWORD}
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

volumes:
  sonarqube_data: 
  sonarqube_extensions: 
  sonarqube_logs: 