volumes:
  ms-sql-data:
  ms-sql-tempdb:
  event-store-db-data:
  event-store-db-logs:
  kafka-data:
  mongo-db-data:
  seq-data:
  prometheus-data:
  gf-logs:
  gf-data:
  alloy-data:
  loki-data:
  tempo-data:
  gf-provisioning:
  elasticsearch-data:
  registry:
